name: Example workflow

on:
  schedule:
    - cron: '*/5 * * * *'   # co 5 minut, cały tydzień, weekendy też
  workflow_dispatch:        # umożliwia uruchomienie ręczne

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Test run
        run: echo "Workflow działa!"