name: Uruchamianie bota co 10 minut

on:
  schedule:
    - cron: '*/10 * * * *'  # co 10 minut
  workflow_dispatch:        # pozwala też uruchomić ręcznie w GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # lub inna wersja

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 python-telegram-bot

    - name: Run bot script
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python bot.py
