name: Ogłoszenia Tarnów

on:
  schedule:
    - cron: "*/10 * * * *"  # co 10 minut
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Ustaw Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Zainstaluj zależności
        run: pip install beautifulsoup4 requests
      - name: Uruchom bota
        run: python bot.py