name: Check Announcements

on:
  schedule:
    - cron: '*/20 6-20 * * 1-5'  # Co 20 minut, 08:00–22:00 czasu PL, pon–pt
  workflow_dispatch:             # Ręczne uruchamianie z GitHub UI

jobs:
  run_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Python script
        run: python bot.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}