name: Co 10 minut od 1 do 23 godziny

on:
  schedule:
    - cron: "*/10 1-23 * * *"  # co 10 minut w godzinach od 1 do 23
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow uruchomiony co 10 minut od godziny 1 do 23!"
