- name: Run bot script (codziennie 6:00–22:59 PL)
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          export TZ=Europe/Warsaw
          date
          HOUR=$(date +"%H")

          echo "Aktualna godzina: $HOUR"

          if [ "$HOUR" -ge 6 ] && [ "$HOUR" -le 22 ]; then
            echo "✅ W dozwolonym czasie – uruchamiam bota"
            python bot.py
          else
            echo "⛔ Poza dozwolonymi godzinami – pomijam uruchomienie"
          fi