name: Run every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # co 5 minut przez cały tydzień

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run script or command
        run: echo "Działa co 5 minut, przez cały tydzień!"