name: Run Telegram Bot

on:
  workflow_dispatch:   # pozwala ręcznie uruchomić workflow
  schedule:
    - cron: '*/30 * * * *'  # uruchamiaj co 30 minut (możesz zmienić)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run bot script
        run: python bot.py