name: Check Announcements

on:
  schedule:
    - cron: '*/5 1-23 * * 1-5'   # Co 5 minut, godziny 1:00-23:59 UTC, pon–pt
  workflow_dispatch:             # Ręczne uruchomienie

jobs:
  run_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Python script
        run: python bot.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}