name: Run Telegram Bot

on:
  schedule:
    - cron: "*/10 * * * *"  # uruchamia co 10 minut
  workflow_dispatch:        # pozwala też uruchomić ręcznie z GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
