name: Run Bot Simple

on:
  workflow_dispatch:
  schedule:
    # Co 20 minut od 5:00 do 20:40 czasu letniego w Polsce (CEST = UTC+2)
    # W UTC to godziny 3:00 - 18:40
    - cron: '0,20,40 3-18 * * 1-5'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run bot only on workdays 5–20 PL time
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          export TZ=Europe/Warsaw
          HOUR=$(date +'%H')
          DOW=$(date +'%u')
          echo "Godzina (PL): $HOUR, Dzień tygodnia: $DOW"

          if [ "$DOW" -le 5 ] && [ "$HOUR" -ge 5 ] && [ "$HOUR" -lt 21 ]; then
            echo "Uruchamiam bota"
            python bot.py
          else
            echo "Poza godzinami pracy, pomijam"
          fi