name: Run Telegram Bot

on:
  schedule:
    - cron: "*/15 6-22 * * *"  # co 15 minut, od godziny 6 do 22
  workflow_dispatch:            # ręczne uruchomienie

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot script (tylko dni robocze 6:00–22:59 PL)
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          export TZ=Europe/Warsaw
          HOUR=$(date +"%H")
          DOW=$(date +"%u")  # 1 = pon, 7 = niedz.

          echo "Aktualna godzina: $HOUR"
          echo "Dzień tygodnia: $DOW"

          if [ "$DOW" -le 5 ] && [ "$HOUR" -ge 6 ] && [ "$HOUR" -le 22 ]; then
            echo "✅ W dozwolonym czasie – uruchamiam bota"
            python bot.py
          else
            echo "⛔ Poza dozwolonymi godzinami – pomijam uruchomienie"
          fi
