name: Run every 30 minutes

on:
  schedule:
    - cron: "*/30 * * * *"  # co 30 minut, każdego dnia, całego tygodnia

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run script or command
        run: echo "Działa co 30 minut, przez cały tydzień!"
